var dir_cc6b7e091ef8b4ae9b3cde82c25c1d88 =
[
    [ "AnalyticsViewModel.cs", "_analytics_view_model_8cs_source.html", null ],
    [ "CompetitionViewModel.cs", "_competition_view_model_8cs_source.html", null ],
    [ "CreateDocumentsViewModel.cs", "_create_documents_view_model_8cs_source.html", null ],
    [ "DocumentPlaceholderViewConfig.cs", "_document_placeholder_view_config_8cs_source.html", null ],
    [ "DropAllowedHandler.cs", "_drop_allowed_handler_8cs_source.html", null ],
    [ "DropAllowedHandlerParkingLot.cs", "_drop_allowed_handler_parking_lot_8cs_source.html", null ],
    [ "DropAllowedSameTypeAndNotSortedHandler.cs", "_drop_allowed_same_type_and_not_sorted_handler_8cs_source.html", null ],
    [ "FriendGroupViewModel.cs", "_friend_group_view_model_8cs_source.html", null ],
    [ "HighlightPersonStartModes.cs", "_highlight_person_start_modes_8cs_source.html", null ],
    [ "MainViewModel.cs", "_main_view_model_8cs_source.html", null ],
    [ "PeopleViewModel.cs", "_people_view_model_8cs_source.html", null ],
    [ "PrepareRacesViewModel.cs", "_prepare_races_view_model_8cs_source.html", null ],
    [ "ResultsViewModel.cs", "_results_view_model_8cs_source.html", null ],
    [ "SettingsViewModel.cs", "_settings_view_model_8cs_source.html", null ],
    [ "ShellViewModel.cs", "_shell_view_model_8cs_source.html", null ],
    [ "TimeInputPersonStartFilterModes.cs", "_time_input_person_start_filter_modes_8cs_source.html", null ],
    [ "TimeInputViewModel.cs", "_time_input_view_model_8cs_source.html", null ],
    [ "WorkspaceManagerViewModel.cs", "_workspace_manager_view_model_8cs_source.html", null ],
    [ "WorkspaceSettingEditorTypes.cs", "_workspace_setting_editor_types_8cs_source.html", null ],
    [ "WorkspaceSettingsGroupViewModel.cs", "_workspace_settings_group_view_model_8cs_source.html", null ],
    [ "WorkspaceSettingViewConfig.cs", "_workspace_setting_view_config_8cs_source.html", null ],
    [ "WorkspaceSettingViewConfigs.cs", "_workspace_setting_view_configs_8cs_source.html", null ],
    [ "WorkspaceSettingViewModel.cs", "_workspace_setting_view_model_8cs_source.html", null ],
    [ "WorkspaceViewModel.cs", "_workspace_view_model_8cs_source.html", null ]
];