var namespace_vereinsmeisterschaften_1_1_template_selectors =
[
    [ "MenuItemTemplateSelector", "class_vereinsmeisterschaften_1_1_template_selectors_1_1_menu_item_template_selector.html", "class_vereinsmeisterschaften_1_1_template_selectors_1_1_menu_item_template_selector" ]
];