//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vereinsmeisterschaften.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vereinsmeisterschaften.Properties.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string FilterPersonStartModes_None {
            get {
                return ResourceManager.GetString("FilterPersonStartModes_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Person ähnelt.
        /// </summary>
        public static string FilterPersonStartModes_Person {
            get {
                return ResourceManager.GetString("FilterPersonStartModes_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Race ID ähnelt.
        /// </summary>
        public static string FilterPersonStartModes_RaceID {
            get {
                return ResourceManager.GetString("FilterPersonStartModes_RaceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Female ähnelt.
        /// </summary>
        public static string Genders_Female {
            get {
                return ResourceManager.GetString("Genders_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Male ähnelt.
        /// </summary>
        public static string Genders_Male {
            get {
                return ResourceManager.GetString("Genders_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance (m) ähnelt.
        /// </summary>
        public static string HighlightPersonStartModes_Distance {
            get {
                return ResourceManager.GetString("HighlightPersonStartModes_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gender ähnelt.
        /// </summary>
        public static string HighlightPersonStartModes_Gender {
            get {
                return ResourceManager.GetString("HighlightPersonStartModes_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string HighlightPersonStartModes_None {
            get {
                return ResourceManager.GetString("HighlightPersonStartModes_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Person ähnelt.
        /// </summary>
        public static string HighlightPersonStartModes_Person {
            get {
                return ResourceManager.GetString("HighlightPersonStartModes_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swimming Style ähnelt.
        /// </summary>
        public static string HighlightPersonStartModes_SwimmingStyle {
            get {
                return ResourceManager.GetString("HighlightPersonStartModes_SwimmingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backstroke ähnelt.
        /// </summary>
        public static string ResultTypes_Backstroke {
            get {
                return ResourceManager.GetString("ResultTypes_Backstroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breaststroke ähnelt.
        /// </summary>
        public static string ResultTypes_Breaststroke {
            get {
                return ResourceManager.GetString("ResultTypes_Breaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Butterfly ähnelt.
        /// </summary>
        public static string ResultTypes_Butterfly {
            get {
                return ResourceManager.GetString("ResultTypes_Butterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freestyle ähnelt.
        /// </summary>
        public static string ResultTypes_Freestyle {
            get {
                return ResourceManager.GetString("ResultTypes_Freestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medley ähnelt.
        /// </summary>
        public static string ResultTypes_Medley {
            get {
                return ResourceManager.GetString("ResultTypes_Medley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overall ähnelt.
        /// </summary>
        public static string ResultTypes_Overall {
            get {
                return ResourceManager.GetString("ResultTypes_Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WaterFlea ähnelt.
        /// </summary>
        public static string ResultTypes_WaterFlea {
            get {
                return ResourceManager.GetString("ResultTypes_WaterFlea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backstroke ähnelt.
        /// </summary>
        public static string SwimmingStyles_Backstroke {
            get {
                return ResourceManager.GetString("SwimmingStyles_Backstroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breaststroke ähnelt.
        /// </summary>
        public static string SwimmingStyles_Breaststroke {
            get {
                return ResourceManager.GetString("SwimmingStyles_Breaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Butterfly ähnelt.
        /// </summary>
        public static string SwimmingStyles_Butterfly {
            get {
                return ResourceManager.GetString("SwimmingStyles_Butterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freestyle ähnelt.
        /// </summary>
        public static string SwimmingStyles_Freestyle {
            get {
                return ResourceManager.GetString("SwimmingStyles_Freestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medley ähnelt.
        /// </summary>
        public static string SwimmingStyles_Medley {
            get {
                return ResourceManager.GetString("SwimmingStyles_Medley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        public static string SwimmingStyles_Unknown {
            get {
                return ResourceManager.GetString("SwimmingStyles_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Water Flea ähnelt.
        /// </summary>
        public static string SwimmingStyles_WaterFlea {
            get {
                return ResourceManager.GetString("SwimmingStyles_WaterFlea", resourceCulture);
            }
        }
    }
}
