//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vereinsmeisterschaften.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlaceholderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlaceholderResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vereinsmeisterschaften.Properties.PlaceholderResources", typeof(PlaceholderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the birth year. ähnelt.
        /// </summary>
        public static string PlaceholderInfoBirthYear {
            get {
                return ResourceManager.GetString("PlaceholderInfoBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the competition ID. ähnelt.
        /// </summary>
        public static string PlaceholderInfoCompetitionID {
            get {
                return ResourceManager.GetString("PlaceholderInfoCompetitionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the competition year.
        ///This only works outside of tables. ähnelt.
        /// </summary>
        public static string PlaceholderInfoCompetitionYear {
            get {
                return ResourceManager.GetString("PlaceholderInfoCompetitionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the distance in m. ähnelt.
        /// </summary>
        public static string PlaceholderInfoDistance {
            get {
                return ResourceManager.GetString("PlaceholderInfoDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the complete name (&lt;first name&gt; &lt;last name&gt;). ähnelt.
        /// </summary>
        public static string PlaceholderInfoName {
            get {
                return ResourceManager.GetString("PlaceholderInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the place in the overall result list. ähnelt.
        /// </summary>
        public static string PlaceholderInfoResultListPlace {
            get {
                return ResourceManager.GetString("PlaceholderInfoResultListPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the highest score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScore {
            get {
                return ResourceManager.GetString("PlaceholderInfoScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the swimming style. ähnelt.
        /// </summary>
        public static string PlaceholderInfoSwimmingStyle {
            get {
                return ResourceManager.GetString("PlaceholderInfoSwimmingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Placeholder available ähnelt.
        /// </summary>
        public static string PlaceholderLegendAvailable {
            get {
                return ResourceManager.GetString("PlaceholderLegendAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Placeholder available (with postfix up to this number)
        ///e.g. &quot;3&quot; -&gt; %Name1%, %Name2%, %Name3% available beside %Name% ähnelt.
        /// </summary>
        public static string PlaceholderLegendAvailableWithPostfix {
            get {
                return ResourceManager.GetString("PlaceholderLegendAvailableWithPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Platzhalter nicht verfügbar ähnelt.
        /// </summary>
        public static string PlaceholderLegendNotAvailable {
            get {
                return ResourceManager.GetString("PlaceholderLegendNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birth Year ähnelt.
        /// </summary>
        public static string PlaceholderNameBirthYear {
            get {
                return ResourceManager.GetString("PlaceholderNameBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition ID ähnelt.
        /// </summary>
        public static string PlaceholderNameCompetitionID {
            get {
                return ResourceManager.GetString("PlaceholderNameCompetitionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition Year ähnelt.
        /// </summary>
        public static string PlaceholderNameCompetitionYear {
            get {
                return ResourceManager.GetString("PlaceholderNameCompetitionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance ähnelt.
        /// </summary>
        public static string PlaceholderNameDistance {
            get {
                return ResourceManager.GetString("PlaceholderNameDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string PlaceholderNameName {
            get {
                return ResourceManager.GetString("PlaceholderNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result List Place ähnelt.
        /// </summary>
        public static string PlaceholderNameResultListPlace {
            get {
                return ResourceManager.GetString("PlaceholderNameResultListPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score ähnelt.
        /// </summary>
        public static string PlaceholderNameScore {
            get {
                return ResourceManager.GetString("PlaceholderNameScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swimming Style ähnelt.
        /// </summary>
        public static string PlaceholderNameSwimmingStyle {
            get {
                return ResourceManager.GetString("PlaceholderNameSwimmingStyle", resourceCulture);
            }
        }
    }
}
