//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vereinsmeisterschaften.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlaceholderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlaceholderResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vereinsmeisterschaften.Properties.PlaceholderResources", typeof(PlaceholderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics ähnelt.
        /// </summary>
        public static string PlaceholderGroupAnalytics {
            get {
                return ResourceManager.GetString("PlaceholderGroupAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string PlaceholderGroupGeneral {
            get {
                return ResourceManager.GetString("PlaceholderGroupGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Person details ähnelt.
        /// </summary>
        public static string PlaceholderGroupPersondetails {
            get {
                return ResourceManager.GetString("PlaceholderGroupPersondetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scores ähnelt.
        /// </summary>
        public static string PlaceholderGroupScores {
            get {
                return ResourceManager.GetString("PlaceholderGroupScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Times ähnelt.
        /// </summary>
        public static string PlaceholderGroupTimes {
            get {
                return ResourceManager.GetString("PlaceholderGroupTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert an overview of the number of active persons per birth year. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsAgeDistribution {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsAgeDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert an overview of the distances between the starts of a person. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsDistancesBetweenStarts {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsDistancesBetweenStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of female persons. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsGenderPersonsFemaleCount {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsGenderPersonsFemaleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the percentage of female persons. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsGenderPersonsFemalePercentage {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsGenderPersonsFemalePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of male persons. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsGenderPersonsMaleCount {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsGenderPersonsMaleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of male persons. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsGenderPersonsMalePercentage {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsGenderPersonsMalePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of female starts. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsGenderStartsFemaleCount {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsGenderStartsFemaleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the percentage of female starts. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsGenderStartsFemalePercentage {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsGenderStartsFemalePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of male starts. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsGenderStartsMaleCount {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsGenderStartsMaleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of male starts. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsGenderStartsMalePercentage {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsGenderStartsMalePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of active persons. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsPersonCountersNumberActivePeople {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsPersonCountersNumberActivePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of inactive persons. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsPersonCountersNumberInactivePeople {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsPersonCountersNumberInactivePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the total number of persons. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsPersonCountersNumberPeople {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsPersonCountersNumberPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert an overview of the birth years per result place. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsPlacesAgeDistribution {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsPlacesAgeDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert an overview of the birth years per race. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsRacesAges {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsRacesAges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert an overview of the number of valid starts per distance. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsStartDistances {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsStartDistances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of inactive starts. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsStartsCountersNumberInactiveStarts {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsStartsCountersNumberInactiveStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the total number of starts. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsStartsCountersNumberStarts {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsStartsCountersNumberStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of starts with missing competition. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsStartsCountersNumberStartsWithMissingCompetition {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsStartsCountersNumberStartsWithMissingCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of valid starts. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsStartsCountersNumberValidStarts {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsStartsCountersNumberValidStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert an overview of the number of valid starts per person. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsStartsPerPerson {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsStartsPerPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert an overview of the number of valid starts per swimming style. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAnalyticsStartsPerStyle {
            get {
                return ResourceManager.GetString("PlaceholderInfoAnalyticsStartsPerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the application version. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAppVersion {
            get {
                return ResourceManager.GetString("PlaceholderInfoAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the style of the start with the highest score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoBestStyle {
            get {
                return ResourceManager.GetString("PlaceholderInfoBestStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the birth year. ähnelt.
        /// </summary>
        public static string PlaceholderInfoBirthYear {
            get {
                return ResourceManager.GetString("PlaceholderInfoBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the competition date.
        ///This only works outside of tables. ähnelt.
        /// </summary>
        public static string PlaceholderInfoCompetitionDate {
            get {
                return ResourceManager.GetString("PlaceholderInfoCompetitionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the competition ID. ähnelt.
        /// </summary>
        public static string PlaceholderInfoCompetitionID {
            get {
                return ResourceManager.GetString("PlaceholderInfoCompetitionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the competition year.
        ///This only works outside of tables. ähnelt.
        /// </summary>
        public static string PlaceholderInfoCompetitionYear {
            get {
                return ResourceManager.GetString("PlaceholderInfoCompetitionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the distance in m. ähnelt.
        /// </summary>
        public static string PlaceholderInfoDistance {
            get {
                return ResourceManager.GetString("PlaceholderInfoDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the first name. ähnelt.
        /// </summary>
        public static string PlaceholderInfoFirstName {
            get {
                return ResourceManager.GetString("PlaceholderInfoFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the gender. ähnelt.
        /// </summary>
        public static string PlaceholderInfoGender {
            get {
                return ResourceManager.GetString("PlaceholderInfoGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the gender as symbol. ähnelt.
        /// </summary>
        public static string PlaceholderInfoGenderSymbol {
            get {
                return ResourceManager.GetString("PlaceholderInfoGenderSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the last name. ähnelt.
        /// </summary>
        public static string PlaceholderInfoLastName {
            get {
                return ResourceManager.GetString("PlaceholderInfoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the complete name (&lt;first name&gt; &lt;last name&gt;). ähnelt.
        /// </summary>
        public static string PlaceholderInfoName {
            get {
                return ResourceManager.GetString("PlaceholderInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of the race beginning with 1. ähnelt.
        /// </summary>
        public static string PlaceholderInfoRaceNumber {
            get {
                return ResourceManager.GetString("PlaceholderInfoRaceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the place in the overall result list. ähnelt.
        /// </summary>
        public static string PlaceholderInfoResultListPlace {
            get {
                return ResourceManager.GetString("PlaceholderInfoResultListPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the highest score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScore {
            get {
                return ResourceManager.GetString("PlaceholderInfoScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the backstroke score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScoreBackstroke {
            get {
                return ResourceManager.GetString("PlaceholderInfoScoreBackstroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the breaststroke score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScoreBreaststroke {
            get {
                return ResourceManager.GetString("PlaceholderInfoScoreBreaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the butterfly score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScoreButterfly {
            get {
                return ResourceManager.GetString("PlaceholderInfoScoreButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the freestyle score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScoreFreestyle {
            get {
                return ResourceManager.GetString("PlaceholderInfoScoreFreestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the medley score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScoreMedley {
            get {
                return ResourceManager.GetString("PlaceholderInfoScoreMedley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the waterflea score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScoreWaterflea {
            get {
                return ResourceManager.GetString("PlaceholderInfoScoreWaterflea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the swimming style. ähnelt.
        /// </summary>
        public static string PlaceholderInfoSwimmingStyle {
            get {
                return ResourceManager.GetString("PlaceholderInfoSwimmingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the backstroke time. ähnelt.
        /// </summary>
        public static string PlaceholderInfoTimeBackstroke {
            get {
                return ResourceManager.GetString("PlaceholderInfoTimeBackstroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the breaststroke time. ähnelt.
        /// </summary>
        public static string PlaceholderInfoTimeBreaststroke {
            get {
                return ResourceManager.GetString("PlaceholderInfoTimeBreaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the butterfly time. ähnelt.
        /// </summary>
        public static string PlaceholderInfoTimeButterfly {
            get {
                return ResourceManager.GetString("PlaceholderInfoTimeButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the freestyle time. ähnelt.
        /// </summary>
        public static string PlaceholderInfoTimeFreestyle {
            get {
                return ResourceManager.GetString("PlaceholderInfoTimeFreestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the medley time. ähnelt.
        /// </summary>
        public static string PlaceholderInfoTimeMedley {
            get {
                return ResourceManager.GetString("PlaceholderInfoTimeMedley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the waterflea time. ähnelt.
        /// </summary>
        public static string PlaceholderInfoTimeWaterflea {
            get {
                return ResourceManager.GetString("PlaceholderInfoTimeWaterflea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the path to the workspace. ähnelt.
        /// </summary>
        public static string PlaceholderInfoWorkspacePath {
            get {
                return ResourceManager.GetString("PlaceholderInfoWorkspacePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Placeholder available ähnelt.
        /// </summary>
        public static string PlaceholderLegendAvailable {
            get {
                return ResourceManager.GetString("PlaceholderLegendAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Placeholder available (with postfix up to this number)
        ///e.g. &quot;3&quot; -&gt; %Name1%, %Name2%, %Name3% available beside %Name% ähnelt.
        /// </summary>
        public static string PlaceholderLegendAvailableWithPostfix {
            get {
                return ResourceManager.GetString("PlaceholderLegendAvailableWithPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Platzhalter nicht verfügbar ähnelt.
        /// </summary>
        public static string PlaceholderLegendNotAvailable {
            get {
                return ResourceManager.GetString("PlaceholderLegendNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Age Distribution ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsAgeDistribution {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsAgeDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsDistancesBetweenStarts {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsDistancesBetweenStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Gender Persons: Female Count ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsGenderPersonsFemaleCount {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsGenderPersonsFemaleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Gender Persons: Female Percentage ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsGenderPersonsFemalePercentage {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsGenderPersonsFemalePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Gender Persons: Male Count ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsGenderPersonsMaleCount {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsGenderPersonsMaleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Gender Persons: Male Percentage ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsGenderPersonsMalePercentage {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsGenderPersonsMalePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Gender Starts: Female Count ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsGenderStartsFemaleCount {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsGenderStartsFemaleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Gender Starts: Female Percentage ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsGenderStartsFemalePercentage {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsGenderStartsFemalePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Gender Starts: Male Count ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsGenderStartsMaleCount {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsGenderStartsMaleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Gender Starts: Male Percentage ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsGenderStartsMalePercentage {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsGenderStartsMalePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Person Counters: Number active People ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsPersonCountersNumberActivePeople {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsPersonCountersNumberActivePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Person Counters: Number inactive People ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsPersonCountersNumberInactivePeople {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsPersonCountersNumberInactivePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Person Counters: Number People ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsPersonCountersNumberPeople {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsPersonCountersNumberPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Places Age Distribution ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsPlacesAgeDistribution {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsPlacesAgeDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Races Ages ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsRacesAges {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsRacesAges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Start Distances ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsStartDistances {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsStartDistances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Starts Counters: Number inactive Starts ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsStartsCountersNumberInactiveStarts {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsStartsCountersNumberInactiveStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Starts Counters: Number Starts ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsStartsCountersNumberStarts {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsStartsCountersNumberStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Starts Counters: Number Starts with missing competition ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsStartsCountersNumberStartsWithMissingCompetition {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsStartsCountersNumberStartsWithMissingCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Starts Counters: Number valid Starts ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsStartsCountersNumberValidStarts {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsStartsCountersNumberValidStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Starts Per Person ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsStartsPerPerson {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsStartsPerPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics: Starts Per Style ähnelt.
        /// </summary>
        public static string PlaceholderNameAnalyticsStartsPerStyle {
            get {
                return ResourceManager.GetString("PlaceholderNameAnalyticsStartsPerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App Version ähnelt.
        /// </summary>
        public static string PlaceholderNameAppVersion {
            get {
                return ResourceManager.GetString("PlaceholderNameAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Best Style ähnelt.
        /// </summary>
        public static string PlaceholderNameBestStyle {
            get {
                return ResourceManager.GetString("PlaceholderNameBestStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birth Year ähnelt.
        /// </summary>
        public static string PlaceholderNameBirthYear {
            get {
                return ResourceManager.GetString("PlaceholderNameBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition Date ähnelt.
        /// </summary>
        public static string PlaceholderNameCompetitionDate {
            get {
                return ResourceManager.GetString("PlaceholderNameCompetitionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition ID ähnelt.
        /// </summary>
        public static string PlaceholderNameCompetitionID {
            get {
                return ResourceManager.GetString("PlaceholderNameCompetitionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition Year ähnelt.
        /// </summary>
        public static string PlaceholderNameCompetitionYear {
            get {
                return ResourceManager.GetString("PlaceholderNameCompetitionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance ähnelt.
        /// </summary>
        public static string PlaceholderNameDistance {
            get {
                return ResourceManager.GetString("PlaceholderNameDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name ähnelt.
        /// </summary>
        public static string PlaceholderNameFirstName {
            get {
                return ResourceManager.GetString("PlaceholderNameFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gender ähnelt.
        /// </summary>
        public static string PlaceholderNameGender {
            get {
                return ResourceManager.GetString("PlaceholderNameGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gender (Symbol) ähnelt.
        /// </summary>
        public static string PlaceholderNameGenderSymbol {
            get {
                return ResourceManager.GetString("PlaceholderNameGenderSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Name ähnelt.
        /// </summary>
        public static string PlaceholderNameLastName {
            get {
                return ResourceManager.GetString("PlaceholderNameLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string PlaceholderNameName {
            get {
                return ResourceManager.GetString("PlaceholderNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Race Number ähnelt.
        /// </summary>
        public static string PlaceholderNameRaceNumber {
            get {
                return ResourceManager.GetString("PlaceholderNameRaceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result List Place ähnelt.
        /// </summary>
        public static string PlaceholderNameResultListPlace {
            get {
                return ResourceManager.GetString("PlaceholderNameResultListPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score ähnelt.
        /// </summary>
        public static string PlaceholderNameScore {
            get {
                return ResourceManager.GetString("PlaceholderNameScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Backstroke ähnelt.
        /// </summary>
        public static string PlaceholderNameScoreBackstroke {
            get {
                return ResourceManager.GetString("PlaceholderNameScoreBackstroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Breaststroke ähnelt.
        /// </summary>
        public static string PlaceholderNameScoreBreaststroke {
            get {
                return ResourceManager.GetString("PlaceholderNameScoreBreaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Butterfly ähnelt.
        /// </summary>
        public static string PlaceholderNameScoreButterfly {
            get {
                return ResourceManager.GetString("PlaceholderNameScoreButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Freestyle ähnelt.
        /// </summary>
        public static string PlaceholderNameScoreFreestyle {
            get {
                return ResourceManager.GetString("PlaceholderNameScoreFreestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Medley ähnelt.
        /// </summary>
        public static string PlaceholderNameScoreMedley {
            get {
                return ResourceManager.GetString("PlaceholderNameScoreMedley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Waterflea ähnelt.
        /// </summary>
        public static string PlaceholderNameScoreWaterflea {
            get {
                return ResourceManager.GetString("PlaceholderNameScoreWaterflea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swimming Style ähnelt.
        /// </summary>
        public static string PlaceholderNameSwimmingStyle {
            get {
                return ResourceManager.GetString("PlaceholderNameSwimmingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Backstroke ähnelt.
        /// </summary>
        public static string PlaceholderNameTimeBackstroke {
            get {
                return ResourceManager.GetString("PlaceholderNameTimeBackstroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Breaststroke ähnelt.
        /// </summary>
        public static string PlaceholderNameTimeBreaststroke {
            get {
                return ResourceManager.GetString("PlaceholderNameTimeBreaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Butterfly ähnelt.
        /// </summary>
        public static string PlaceholderNameTimeButterfly {
            get {
                return ResourceManager.GetString("PlaceholderNameTimeButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Freestyle ähnelt.
        /// </summary>
        public static string PlaceholderNameTimeFreestyle {
            get {
                return ResourceManager.GetString("PlaceholderNameTimeFreestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Medley ähnelt.
        /// </summary>
        public static string PlaceholderNameTimeMedley {
            get {
                return ResourceManager.GetString("PlaceholderNameTimeMedley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Waterflea ähnelt.
        /// </summary>
        public static string PlaceholderNameTimeWaterflea {
            get {
                return ResourceManager.GetString("PlaceholderNameTimeWaterflea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workspace Path ähnelt.
        /// </summary>
        public static string PlaceholderNameWorkspacePath {
            get {
                return ResourceManager.GetString("PlaceholderNameWorkspacePath", resourceCulture);
            }
        }
    }
}
