//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vereinsmeisterschaften.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlaceholderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlaceholderResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vereinsmeisterschaften.Properties.PlaceholderResources", typeof(PlaceholderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the application version. ähnelt.
        /// </summary>
        public static string PlaceholderInfoAppVersion {
            get {
                return ResourceManager.GetString("PlaceholderInfoAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the style of the start with the highest score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoBestStyle {
            get {
                return ResourceManager.GetString("PlaceholderInfoBestStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the birth year. ähnelt.
        /// </summary>
        public static string PlaceholderInfoBirthYear {
            get {
                return ResourceManager.GetString("PlaceholderInfoBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the competition date.
        ///This only works outside of tables. ähnelt.
        /// </summary>
        public static string PlaceholderInfoCompetitionDate {
            get {
                return ResourceManager.GetString("PlaceholderInfoCompetitionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the competition ID. ähnelt.
        /// </summary>
        public static string PlaceholderInfoCompetitionID {
            get {
                return ResourceManager.GetString("PlaceholderInfoCompetitionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the competition year.
        ///This only works outside of tables. ähnelt.
        /// </summary>
        public static string PlaceholderInfoCompetitionYear {
            get {
                return ResourceManager.GetString("PlaceholderInfoCompetitionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the distance in m. ähnelt.
        /// </summary>
        public static string PlaceholderInfoDistance {
            get {
                return ResourceManager.GetString("PlaceholderInfoDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the first name. ähnelt.
        /// </summary>
        public static string PlaceholderInfoFirstName {
            get {
                return ResourceManager.GetString("PlaceholderInfoFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the gender. ähnelt.
        /// </summary>
        public static string PlaceholderInfoGender {
            get {
                return ResourceManager.GetString("PlaceholderInfoGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the gender as symbol. ähnelt.
        /// </summary>
        public static string PlaceholderInfoGenderSymbol {
            get {
                return ResourceManager.GetString("PlaceholderInfoGenderSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the last name. ähnelt.
        /// </summary>
        public static string PlaceholderInfoLastName {
            get {
                return ResourceManager.GetString("PlaceholderInfoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the complete name (&lt;first name&gt; &lt;last name&gt;). ähnelt.
        /// </summary>
        public static string PlaceholderInfoName {
            get {
                return ResourceManager.GetString("PlaceholderInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the number of the race beginning with 1. ähnelt.
        /// </summary>
        public static string PlaceholderInfoRaceNumber {
            get {
                return ResourceManager.GetString("PlaceholderInfoRaceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the place in the overall result list. ähnelt.
        /// </summary>
        public static string PlaceholderInfoResultListPlace {
            get {
                return ResourceManager.GetString("PlaceholderInfoResultListPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the highest score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScore {
            get {
                return ResourceManager.GetString("PlaceholderInfoScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the backstroke score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScoreBackstroke {
            get {
                return ResourceManager.GetString("PlaceholderInfoScoreBackstroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the breaststroke score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScoreBreaststroke {
            get {
                return ResourceManager.GetString("PlaceholderInfoScoreBreaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the butterfly score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScoreButterfly {
            get {
                return ResourceManager.GetString("PlaceholderInfoScoreButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the freestyle score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScoreFreestyle {
            get {
                return ResourceManager.GetString("PlaceholderInfoScoreFreestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the medley score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScoreMedley {
            get {
                return ResourceManager.GetString("PlaceholderInfoScoreMedley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the waterflea score. ähnelt.
        /// </summary>
        public static string PlaceholderInfoScoreWaterflea {
            get {
                return ResourceManager.GetString("PlaceholderInfoScoreWaterflea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the swimming style. ähnelt.
        /// </summary>
        public static string PlaceholderInfoSwimmingStyle {
            get {
                return ResourceManager.GetString("PlaceholderInfoSwimmingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the backstroke time. ähnelt.
        /// </summary>
        public static string PlaceholderInfoTimeBackstroke {
            get {
                return ResourceManager.GetString("PlaceholderInfoTimeBackstroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the breaststroke time. ähnelt.
        /// </summary>
        public static string PlaceholderInfoTimeBreaststroke {
            get {
                return ResourceManager.GetString("PlaceholderInfoTimeBreaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the butterfly time. ähnelt.
        /// </summary>
        public static string PlaceholderInfoTimeButterfly {
            get {
                return ResourceManager.GetString("PlaceholderInfoTimeButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the freestyle time. ähnelt.
        /// </summary>
        public static string PlaceholderInfoTimeFreestyle {
            get {
                return ResourceManager.GetString("PlaceholderInfoTimeFreestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the medley time. ähnelt.
        /// </summary>
        public static string PlaceholderInfoTimeMedley {
            get {
                return ResourceManager.GetString("PlaceholderInfoTimeMedley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the waterflea time. ähnelt.
        /// </summary>
        public static string PlaceholderInfoTimeWaterflea {
            get {
                return ResourceManager.GetString("PlaceholderInfoTimeWaterflea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use these placeholders to insert the path to the workspace. ähnelt.
        /// </summary>
        public static string PlaceholderInfoWorkspacePath {
            get {
                return ResourceManager.GetString("PlaceholderInfoWorkspacePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Placeholder available ähnelt.
        /// </summary>
        public static string PlaceholderLegendAvailable {
            get {
                return ResourceManager.GetString("PlaceholderLegendAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Placeholder available (with postfix up to this number)
        ///e.g. &quot;3&quot; -&gt; %Name1%, %Name2%, %Name3% available beside %Name% ähnelt.
        /// </summary>
        public static string PlaceholderLegendAvailableWithPostfix {
            get {
                return ResourceManager.GetString("PlaceholderLegendAvailableWithPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Platzhalter nicht verfügbar ähnelt.
        /// </summary>
        public static string PlaceholderLegendNotAvailable {
            get {
                return ResourceManager.GetString("PlaceholderLegendNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App Version ähnelt.
        /// </summary>
        public static string PlaceholderNameAppVersion {
            get {
                return ResourceManager.GetString("PlaceholderNameAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Best Style ähnelt.
        /// </summary>
        public static string PlaceholderNameBestStyle {
            get {
                return ResourceManager.GetString("PlaceholderNameBestStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birth Year ähnelt.
        /// </summary>
        public static string PlaceholderNameBirthYear {
            get {
                return ResourceManager.GetString("PlaceholderNameBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition Date ähnelt.
        /// </summary>
        public static string PlaceholderNameCompetitionDate {
            get {
                return ResourceManager.GetString("PlaceholderNameCompetitionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition ID ähnelt.
        /// </summary>
        public static string PlaceholderNameCompetitionID {
            get {
                return ResourceManager.GetString("PlaceholderNameCompetitionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition Year ähnelt.
        /// </summary>
        public static string PlaceholderNameCompetitionYear {
            get {
                return ResourceManager.GetString("PlaceholderNameCompetitionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance ähnelt.
        /// </summary>
        public static string PlaceholderNameDistance {
            get {
                return ResourceManager.GetString("PlaceholderNameDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name ähnelt.
        /// </summary>
        public static string PlaceholderNameFirstName {
            get {
                return ResourceManager.GetString("PlaceholderNameFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gender ähnelt.
        /// </summary>
        public static string PlaceholderNameGender {
            get {
                return ResourceManager.GetString("PlaceholderNameGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gender (Symbol) ähnelt.
        /// </summary>
        public static string PlaceholderNameGenderSymbol {
            get {
                return ResourceManager.GetString("PlaceholderNameGenderSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Name ähnelt.
        /// </summary>
        public static string PlaceholderNameLastName {
            get {
                return ResourceManager.GetString("PlaceholderNameLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string PlaceholderNameName {
            get {
                return ResourceManager.GetString("PlaceholderNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Race Number ähnelt.
        /// </summary>
        public static string PlaceholderNameRaceNumber {
            get {
                return ResourceManager.GetString("PlaceholderNameRaceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result List Place ähnelt.
        /// </summary>
        public static string PlaceholderNameResultListPlace {
            get {
                return ResourceManager.GetString("PlaceholderNameResultListPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score ähnelt.
        /// </summary>
        public static string PlaceholderNameScore {
            get {
                return ResourceManager.GetString("PlaceholderNameScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Backstroke ähnelt.
        /// </summary>
        public static string PlaceholderNameScoreBackstroke {
            get {
                return ResourceManager.GetString("PlaceholderNameScoreBackstroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Breaststroke ähnelt.
        /// </summary>
        public static string PlaceholderNameScoreBreaststroke {
            get {
                return ResourceManager.GetString("PlaceholderNameScoreBreaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Butterfly ähnelt.
        /// </summary>
        public static string PlaceholderNameScoreButterfly {
            get {
                return ResourceManager.GetString("PlaceholderNameScoreButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Freestyle ähnelt.
        /// </summary>
        public static string PlaceholderNameScoreFreestyle {
            get {
                return ResourceManager.GetString("PlaceholderNameScoreFreestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Medley ähnelt.
        /// </summary>
        public static string PlaceholderNameScoreMedley {
            get {
                return ResourceManager.GetString("PlaceholderNameScoreMedley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Waterflea ähnelt.
        /// </summary>
        public static string PlaceholderNameScoreWaterflea {
            get {
                return ResourceManager.GetString("PlaceholderNameScoreWaterflea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swimming Style ähnelt.
        /// </summary>
        public static string PlaceholderNameSwimmingStyle {
            get {
                return ResourceManager.GetString("PlaceholderNameSwimmingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Backstroke ähnelt.
        /// </summary>
        public static string PlaceholderNameTimeBackstroke {
            get {
                return ResourceManager.GetString("PlaceholderNameTimeBackstroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Breaststroke ähnelt.
        /// </summary>
        public static string PlaceholderNameTimeBreaststroke {
            get {
                return ResourceManager.GetString("PlaceholderNameTimeBreaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Butterfly ähnelt.
        /// </summary>
        public static string PlaceholderNameTimeButterfly {
            get {
                return ResourceManager.GetString("PlaceholderNameTimeButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Freestyle ähnelt.
        /// </summary>
        public static string PlaceholderNameTimeFreestyle {
            get {
                return ResourceManager.GetString("PlaceholderNameTimeFreestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Medley ähnelt.
        /// </summary>
        public static string PlaceholderNameTimeMedley {
            get {
                return ResourceManager.GetString("PlaceholderNameTimeMedley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Waterflea ähnelt.
        /// </summary>
        public static string PlaceholderNameTimeWaterflea {
            get {
                return ResourceManager.GetString("PlaceholderNameTimeWaterflea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workspace Path ähnelt.
        /// </summary>
        public static string PlaceholderNameWorkspacePath {
            get {
                return ResourceManager.GetString("PlaceholderNameWorkspacePath", resourceCulture);
            }
        }
    }
}
