//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vereinsmeisterschaften.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vereinsmeisterschaften.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active ähnelt.
        /// </summary>
        public static string ActiveString {
            get {
                return ResourceManager.GetString("ActiveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new empty race ähnelt.
        /// </summary>
        public static string AddEmptyRaceString {
            get {
                return ResourceManager.GetString("AddEmptyRaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new competition ähnelt.
        /// </summary>
        public static string AddNewCompetition {
            get {
                return ResourceManager.GetString("AddNewCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new friend group ähnelt.
        /// </summary>
        public static string AddNewFriendGroupString {
            get {
                return ResourceManager.GetString("AddNewFriendGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new person ähnelt.
        /// </summary>
        public static string AddNewPerson {
            get {
                return ResourceManager.GetString("AddNewPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Variant ähnelt.
        /// </summary>
        public static string AddRaceVariantString {
            get {
                return ResourceManager.GetString("AddRaceVariantString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Age ähnelt.
        /// </summary>
        public static string AgeString {
            get {
                return ResourceManager.GetString("AgeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nothing left to do.All Starts are assigned. ähnelt.
        /// </summary>
        public static string AllStartsAssignedString {
            get {
                return ResourceManager.GetString("AllStartsAssignedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics ähnelt.
        /// </summary>
        public static string AnalyticsPageTitle {
            get {
                return ResourceManager.GetString("AnalyticsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of active persons per birth year ähnelt.
        /// </summary>
        public static string AnalyticsWidgetAgeDistributionTitle {
            get {
                return ResourceManager.GetString("AnalyticsWidgetAgeDistributionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distances between the starts of a person ähnelt.
        /// </summary>
        public static string AnalyticsWidgetDistancesBetweenStartsTitle {
            get {
                return ResourceManager.GetString("AnalyticsWidgetDistancesBetweenStartsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gender distribution of active persons ähnelt.
        /// </summary>
        public static string AnalyticsWidgetGenderPersonsTitle {
            get {
                return ResourceManager.GetString("AnalyticsWidgetGenderPersonsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gender distribution of valid starts ähnelt.
        /// </summary>
        public static string AnalyticsWidgetGenderStartsTitle {
            get {
                return ResourceManager.GetString("AnalyticsWidgetGenderStartsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number Persons ähnelt.
        /// </summary>
        public static string AnalyticsWidgetPersonCountersTitle {
            get {
                return ResourceManager.GetString("AnalyticsWidgetPersonCountersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birth years per result place ähnelt.
        /// </summary>
        public static string AnalyticsWidgetPlacesAgeDistributionTitle {
            get {
                return ResourceManager.GetString("AnalyticsWidgetPlacesAgeDistributionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of valid starts per distance ähnelt.
        /// </summary>
        public static string AnalyticsWidgetStartDistancesTitle {
            get {
                return ResourceManager.GetString("AnalyticsWidgetStartDistancesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number Starts ähnelt.
        /// </summary>
        public static string AnalyticsWidgetStartsCountersTitle {
            get {
                return ResourceManager.GetString("AnalyticsWidgetStartsCountersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of valid starts per person ähnelt.
        /// </summary>
        public static string AnalyticsWidgetStartsPerPersonTitle {
            get {
                return ResourceManager.GetString("AnalyticsWidgetStartsPerPersonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of valid starts per style ähnelt.
        /// </summary>
        public static string AnalyticsWidgetStartsPerStyleTitle {
            get {
                return ResourceManager.GetString("AnalyticsWidgetStartsPerStyleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vereinsmeisterschaften ähnelt.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available Placeholders ähnelt.
        /// </summary>
        public static string AvailablePlaceholdersString {
            get {
                return ResourceManager.GetString("AvailablePlaceholdersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backstroke ähnelt.
        /// </summary>
        public static string BackstrokeString {
            get {
                return ResourceManager.GetString("BackstrokeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birth Year ähnelt.
        /// </summary>
        public static string BirthYearString {
            get {
                return ResourceManager.GetString("BirthYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breaststroke ähnelt.
        /// </summary>
        public static string BreaststrokeString {
            get {
                return ResourceManager.GetString("BreaststrokeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Butterfly ähnelt.
        /// </summary>
        public static string ButterflyString {
            get {
                return ResourceManager.GetString("ButterflyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculated Score ähnelt.
        /// </summary>
        public static string CalculatedRaceVariantScoreString {
            get {
                return ResourceManager.GetString("CalculatedRaceVariantScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculated Score ähnelt.
        /// </summary>
        public static string CalculatedScoreString {
            get {
                return ResourceManager.GetString("CalculatedScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Races Variants ähnelt.
        /// </summary>
        public static string CalculateRacesVariantsString {
            get {
                return ResourceManager.GetString("CalculateRacesVariantsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Less variants than requested were calculated ({0} / {1}). This can be caused by:
        ///- too high minimum score for the variants
        ///- too less maximum calculation loops ähnelt.
        /// </summary>
        public static string CalculationWarningTooLessVariantsString {
            get {
                return ResourceManager.GetString("CalculationWarningTooLessVariantsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Certificate Template ähnelt.
        /// </summary>
        public static string CertificateTemplatePathString {
            get {
                return ResourceManager.GetString("CertificateTemplatePathString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cleanup races ähnelt.
        /// </summary>
        public static string CleanupRacesString {
            get {
                return ResourceManager.GetString("CleanupRacesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string CloseString {
            get {
                return ResourceManager.GetString("CloseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition Date ähnelt.
        /// </summary>
        public static string CompetitionDateString {
            get {
                return ResourceManager.GetString("CompetitionDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition ID ähnelt.
        /// </summary>
        public static string CompetitionIDString {
            get {
                return ResourceManager.GetString("CompetitionIDString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition missing and start selected ähnelt.
        /// </summary>
        public static string CompetitionMissingAndSelectedString {
            get {
                return ResourceManager.GetString("CompetitionMissingAndSelectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition is missing ähnelt.
        /// </summary>
        public static string CompetitionMissingString {
            get {
                return ResourceManager.GetString("CompetitionMissingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competitions ähnelt.
        /// </summary>
        public static string CompetitionPageTitle {
            get {
                return ResourceManager.GetString("CompetitionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition Search Mode ähnelt.
        /// </summary>
        public static string CompetitionSearchModeString {
            get {
                return ResourceManager.GetString("CompetitionSearchModeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition Year ähnelt.
        /// </summary>
        public static string CompetitionYearString {
            get {
                return ResourceManager.GetString("CompetitionYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Variant ähnelt.
        /// </summary>
        public static string CopyRaceVariantString {
            get {
                return ResourceManager.GetString("CopyRaceVariantString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count ähnelt.
        /// </summary>
        public static string CountString {
            get {
                return ResourceManager.GetString("CountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Certificates were created. ähnelt.
        /// </summary>
        public static string CreateCertificatesResultString {
            get {
                return ResourceManager.GetString("CreateCertificatesResultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Certificates ähnelt.
        /// </summary>
        public static string CreateCertificatesString {
            get {
                return ResourceManager.GetString("CreateCertificatesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Documents ähnelt.
        /// </summary>
        public static string CreateDocumentsPageTitle {
            get {
                return ResourceManager.GetString("CreateDocumentsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overview List was created. ähnelt.
        /// </summary>
        public static string CreateOverviewListResultString {
            get {
                return ResourceManager.GetString("CreateOverviewListResultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Overview List ähnelt.
        /// </summary>
        public static string CreateOverviewListString {
            get {
                return ResourceManager.GetString("CreateOverviewListString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Race Start List was created. ähnelt.
        /// </summary>
        public static string CreateRaceStartListResultString {
            get {
                return ResourceManager.GetString("CreateRaceStartListResultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Race Start List ähnelt.
        /// </summary>
        public static string CreateRaceStartListString {
            get {
                return ResourceManager.GetString("CreateRaceStartListString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result List was created. ähnelt.
        /// </summary>
        public static string CreateResultListDetailResultString {
            get {
                return ResourceManager.GetString("CreateResultListDetailResultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Result List Detail ähnelt.
        /// </summary>
        public static string CreateResultListDetailString {
            get {
                return ResourceManager.GetString("CreateResultListDetailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result List Detail was created. ähnelt.
        /// </summary>
        public static string CreateResultListResultString {
            get {
                return ResourceManager.GetString("CreateResultListResultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Result List ähnelt.
        /// </summary>
        public static string CreateResultListString {
            get {
                return ResourceManager.GetString("CreateResultListString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Forms were created. ähnelt.
        /// </summary>
        public static string CreateTimeFormsResultString {
            get {
                return ResourceManager.GetString("CreateTimeFormsResultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Time Forms ähnelt.
        /// </summary>
        public static string CreateTimeFormsString {
            get {
                return ResourceManager.GetString("CreateTimeFormsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really delete? ähnelt.
        /// </summary>
        public static string DeleteConfirmationTitleString {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really delete the selected variant? This can&apos;t be undone. ähnelt.
        /// </summary>
        public static string DeleteRaceVariantConfirmationString {
            get {
                return ResourceManager.GetString("DeleteRaceVariantConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance between starts ähnelt.
        /// </summary>
        public static string DistanceBetweenStartsString {
            get {
                return ResourceManager.GetString("DistanceBetweenStartsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance ähnelt.
        /// </summary>
        public static string DistanceString {
            get {
                return ResourceManager.GetString("DistanceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document File Types ähnelt.
        /// </summary>
        public static string DocumentFileTypesString {
            get {
                return ResourceManager.GetString("DocumentFileTypesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document output folder ähnelt.
        /// </summary>
        public static string DocumentOutputFolderString {
            get {
                return ResourceManager.GetString("DocumentOutputFolderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t save ähnelt.
        /// </summary>
        public static string DontSaveString {
            get {
                return ResourceManager.GetString("DontSaveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicate Person found ähnelt.
        /// </summary>
        public static string DuplicatePersonFound {
            get {
                return ResourceManager.GetString("DuplicatePersonFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empty Person found (no starts assigned) ähnelt.
        /// </summary>
        public static string EmptyPersonFound {
            get {
                return ResourceManager.GetString("EmptyPersonFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter Mode ähnelt.
        /// </summary>
        public static string FilterModeString {
            get {
                return ResourceManager.GetString("FilterModeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name ähnelt.
        /// </summary>
        public static string FirstNameString {
            get {
                return ResourceManager.GetString("FirstNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freestyle ähnelt.
        /// </summary>
        public static string FreestyleString {
            get {
                return ResourceManager.GetString("FreestyleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Friend Groups ähnelt.
        /// </summary>
        public static string FriendGroupsString {
            get {
                return ResourceManager.GetString("FriendGroupsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gender ähnelt.
        /// </summary>
        public static string GenderString {
            get {
                return ResourceManager.GetString("GenderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Highest Score ähnelt.
        /// </summary>
        public static string HighestScoreString {
            get {
                return ResourceManager.GetString("HighestScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HightlightMode ähnelt.
        /// </summary>
        public static string HighlightModeString {
            get {
                return ResourceManager.GetString("HighlightModeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID ähnelt.
        /// </summary>
        public static string IDString {
            get {
                return ResourceManager.GetString("IDString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inactive ähnelt.
        /// </summary>
        public static string InactiveString {
            get {
                return ResourceManager.GetString("InactiveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string InfoString {
            get {
                return ResourceManager.GetString("InfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is at least one invalid race. ähnelt.
        /// </summary>
        public static string InvalidRacesString {
            get {
                return ResourceManager.GetString("InvalidRacesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iteration Progress ähnelt.
        /// </summary>
        public static string IterationProgressString {
            get {
                return ResourceManager.GetString("IterationProgressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LibreOffice Path ähnelt.
        /// </summary>
        public static string LibreOfficePathString {
            get {
                return ResourceManager.GetString("LibreOfficePathString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Workspace... ähnelt.
        /// </summary>
        public static string LoadWorkspaceString {
            get {
                return ResourceManager.GetString("LoadWorkspaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum number of variant calculation loops ähnelt.
        /// </summary>
        public static string MaxRacesVariantCalculationLoopsString {
            get {
                return ResourceManager.GetString("MaxRacesVariantCalculationLoopsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medley ähnelt.
        /// </summary>
        public static string MedleyString {
            get {
                return ResourceManager.GetString("MedleyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum Race Variant score ähnelt.
        /// </summary>
        public static string MinimumRacesVariantsScoreString {
            get {
                return ResourceManager.GetString("MinimumRacesVariantsScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No data is available ähnelt.
        /// </summary>
        public static string NoDataAvailableWarningString {
            get {
                return ResourceManager.GetString("NoDataAvailableWarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No persistent race variant available ähnelt.
        /// </summary>
        public static string NoPersistentRaceVariantString {
            get {
                return ResourceManager.GetString("NoPersistentRaceVariantString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are not assigned starts. ähnelt.
        /// </summary>
        public static string NotAssignedStartsString {
            get {
                return ResourceManager.GetString("NotAssignedStartsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The template can&apos;t be found
        ///(or is not of type .docx). ähnelt.
        /// </summary>
        public static string NoTemplateAvailableWarningString {
            get {
                return ResourceManager.GetString("NoTemplateAvailableWarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} document(s) ähnelt.
        /// </summary>
        public static string NumberCreatedDocumentsString {
            get {
                return ResourceManager.GetString("NumberCreatedDocumentsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of lanes ähnelt.
        /// </summary>
        public static string NumberOfSwimLanesString {
            get {
                return ResourceManager.GetString("NumberOfSwimLanesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number Persons ähnelt.
        /// </summary>
        public static string NumberPersonsString {
            get {
                return ResourceManager.GetString("NumberPersonsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number Race Variants after calculation ähnelt.
        /// </summary>
        public static string NumberRacesVariantsAfterCalculationString {
            get {
                return ResourceManager.GetString("NumberRacesVariantsAfterCalculationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number Starts ähnelt.
        /// </summary>
        public static string NumberStartsString {
            get {
                return ResourceManager.GetString("NumberStartsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in Explorer ähnelt.
        /// </summary>
        public static string OpenInExplorerString {
            get {
                return ResourceManager.GetString("OpenInExplorerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string OpenString {
            get {
                return ResourceManager.GetString("OpenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overview List Template ähnelt.
        /// </summary>
        public static string OverviewListTemplatePathString {
            get {
                return ResourceManager.GetString("OverviewListTemplatePathString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die People ähnelt.
        /// </summary>
        public static string PeoplePageTitle {
            get {
                return ResourceManager.GetString("PeoplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no assigned competition object. ähnelt.
        /// </summary>
        public static string PersonStartCompetitionObjMissingString {
            get {
                return ResourceManager.GetString("PersonStartCompetitionObjMissingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No dropping allowed here
        ///(incompatible styles/distances or too many items) ähnelt.
        /// </summary>
        public static string PersonStartDragDropErrorString {
            get {
                return ResourceManager.GetString("PersonStartDragDropErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Persons with short pauses ähnelt.
        /// </summary>
        public static string PersonsWithShortPausesString {
            get {
                return ResourceManager.GetString("PersonsWithShortPausesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Placeholder Marker ähnelt.
        /// </summary>
        public static string PlaceholderMarkerString {
            get {
                return ResourceManager.GetString("PlaceholderMarkerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PrepareRaces ähnelt.
        /// </summary>
        public static string PrepareRacesPageTitle {
            get {
                return ResourceManager.GetString("PrepareRacesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priority for style backstroke ähnelt.
        /// </summary>
        public static string PriorityStyleBackstrokeString {
            get {
                return ResourceManager.GetString("PriorityStyleBackstrokeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priority for style breaststroke ähnelt.
        /// </summary>
        public static string PriorityStyleBreaststrokeString {
            get {
                return ResourceManager.GetString("PriorityStyleBreaststrokeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priority for style butterfly ähnelt.
        /// </summary>
        public static string PriorityStyleButterflyString {
            get {
                return ResourceManager.GetString("PriorityStyleButterflyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priority for style freestyle ähnelt.
        /// </summary>
        public static string PriorityStyleFreestyleString {
            get {
                return ResourceManager.GetString("PriorityStyleFreestyleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priority for style medley ähnelt.
        /// </summary>
        public static string PriorityStyleMedleyString {
            get {
                return ResourceManager.GetString("PriorityStyleMedleyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priority for style waterflea ähnelt.
        /// </summary>
        public static string PriorityStyleWaterfleaString {
            get {
                return ResourceManager.GetString("PriorityStyleWaterfleaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The distances in this race don&apos;t match. ähnelt.
        /// </summary>
        public static string RaceDistancesMismatchString {
            get {
                return ResourceManager.GetString("RaceDistancesMismatchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The race is empty (zero starts). ähnelt.
        /// </summary>
        public static string RaceEmptyString {
            get {
                return ResourceManager.GetString("RaceEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Race Start List Template ähnelt.
        /// </summary>
        public static string RaceStartListTemplatePathString {
            get {
                return ResourceManager.GetString("RaceStartListTemplatePathString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The styles in this race don&apos;t match. ähnelt.
        /// </summary>
        public static string RaceStylesMismatchString {
            get {
                return ResourceManager.GetString("RaceStylesMismatchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really remove this competition? This can&apos;t be undone! ähnelt.
        /// </summary>
        public static string RemoveCompetitionConfirmationString {
            get {
                return ResourceManager.GetString("RemoveCompetitionConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Competition ähnelt.
        /// </summary>
        public static string RemoveCompetitionString {
            get {
                return ResourceManager.GetString("RemoveCompetitionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really remove this person? This can&apos;t be undone! ähnelt.
        /// </summary>
        public static string RemovePersonConfirmationString {
            get {
                return ResourceManager.GetString("RemovePersonConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Person ähnelt.
        /// </summary>
        public static string RemovePersonString {
            get {
                return ResourceManager.GetString("RemovePersonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Variant ähnelt.
        /// </summary>
        public static string RemoveRaceVariantString {
            get {
                return ResourceManager.GetString("RemoveRaceVariantString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reorder Variants ähnelt.
        /// </summary>
        public static string ReorderRaceVariantsString {
            get {
                return ResourceManager.GetString("ReorderRaceVariantsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore Layout (exit detailed view) ähnelt.
        /// </summary>
        public static string RestoreLayoutString {
            get {
                return ResourceManager.GetString("RestoreLayoutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result List Detail Template ähnelt.
        /// </summary>
        public static string ResultListDetailTemplatePathString {
            get {
                return ResourceManager.GetString("ResultListDetailTemplatePathString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result List Template ähnelt.
        /// </summary>
        public static string ResultListTemplatePathString {
            get {
                return ResourceManager.GetString("ResultListTemplatePathString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result Place ähnelt.
        /// </summary>
        public static string ResultPlaceString {
            get {
                return ResourceManager.GetString("ResultPlaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Results ähnelt.
        /// </summary>
        public static string ResultsPageTitle {
            get {
                return ResourceManager.GetString("ResultsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competitions saved ähnelt.
        /// </summary>
        public static string SavedStatusCompetitionsString {
            get {
                return ResourceManager.GetString("SavedStatusCompetitionsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Persons saved ähnelt.
        /// </summary>
        public static string SavedStatusPersonsString {
            get {
                return ResourceManager.GetString("SavedStatusPersonsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Races saved ähnelt.
        /// </summary>
        public static string SavedStatusRacesString {
            get {
                return ResourceManager.GetString("SavedStatusRacesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings saved ähnelt.
        /// </summary>
        public static string SavedStatusSettingsString {
            get {
                return ResourceManager.GetString("SavedStatusSettingsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string SaveString {
            get {
                return ResourceManager.GetString("SaveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Workspace... ähnelt.
        /// </summary>
        public static string SaveWorkspaceString {
            get {
                return ResourceManager.GetString("SaveWorkspaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Fractional Digits ähnelt.
        /// </summary>
        public static string ScoreFractionalDigitsString {
            get {
                return ResourceManager.GetString("ScoreFractionalDigitsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Friendships ähnelt.
        /// </summary>
        public static string ScoreFriendshipsString {
            get {
                return ResourceManager.GetString("ScoreFriendshipsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Person Pauses ähnelt.
        /// </summary>
        public static string ScorePersonStartPausesString {
            get {
                return ResourceManager.GetString("ScorePersonStartPausesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Same Style Sequence ähnelt.
        /// </summary>
        public static string ScoreSameStyleSequenceString {
            get {
                return ResourceManager.GetString("ScoreSameStyleSequenceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Single Starts ähnelt.
        /// </summary>
        public static string ScoreSingleStartsString {
            get {
                return ResourceManager.GetString("ScoreSingleStartsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Start Genders ähnelt.
        /// </summary>
        public static string ScoreStartGendersString {
            get {
                return ResourceManager.GetString("ScoreStartGendersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Style Order ähnelt.
        /// </summary>
        public static string ScoreStyleOrderString {
            get {
                return ResourceManager.GetString("ScoreStyleOrderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the settings to the default values. ähnelt.
        /// </summary>
        public static string SettingsDefaultString {
            get {
                return ResourceManager.GetString("SettingsDefaultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document creation settings ähnelt.
        /// </summary>
        public static string SettingsDocumentCreationString {
            get {
                return ResourceManager.GetString("SettingsDocumentCreationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General settings ähnelt.
        /// </summary>
        public static string SettingsGeneralString {
            get {
                return ResourceManager.GetString("SettingsGeneralString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Theme ähnelt.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personalization ähnelt.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Races Variants calculation settings ähnelt.
        /// </summary>
        public static string SettingsRacesVariantsCalculationString {
            get {
                return ResourceManager.GetString("SettingsRacesVariantsCalculationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset the settings to the last persisted state. ähnelt.
        /// </summary>
        public static string SettingsResetString {
            get {
                return ResourceManager.GetString("SettingsResetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analytics ähnelt.
        /// </summary>
        public static string ShellAnalyticsPage {
            get {
                return ResourceManager.GetString("ShellAnalyticsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competitions ähnelt.
        /// </summary>
        public static string ShellCompetitionPage {
            get {
                return ResourceManager.GetString("ShellCompetitionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CreateDocuments ähnelt.
        /// </summary>
        public static string ShellCreateDocumentsPage {
            get {
                return ResourceManager.GetString("ShellCreateDocumentsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go back ähnelt.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open or close navigation ähnelt.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main ähnelt.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die People ähnelt.
        /// </summary>
        public static string ShellPeoplePage {
            get {
                return ResourceManager.GetString("ShellPeoplePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PrepareRaces ähnelt.
        /// </summary>
        public static string ShellPrepareRacesPage {
            get {
                return ResourceManager.GetString("ShellPrepareRacesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Results ähnelt.
        /// </summary>
        public static string ShellResultsPage {
            get {
                return ResourceManager.GetString("ShellResultsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeInput ähnelt.
        /// </summary>
        public static string ShellTimeInputPage {
            get {
                return ResourceManager.GetString("ShellTimeInputPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workspace ähnelt.
        /// </summary>
        public static string ShellWorkspacePage {
            get {
                return ResourceManager.GetString("ShellWorkspacePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Pause Threshold ähnelt.
        /// </summary>
        public static string ShortPauseThresholdString {
            get {
                return ResourceManager.GetString("ShortPauseThresholdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show detailed view ähnelt.
        /// </summary>
        public static string ShowDetailViewString {
            get {
                return ResourceManager.GetString("ShowDetailViewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solution Progress ähnelt.
        /// </summary>
        public static string SolutionProgressString {
            get {
                return ResourceManager.GetString("SolutionProgressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorting ähnelt.
        /// </summary>
        public static string SortString {
            get {
                return ResourceManager.GetString("SortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swimming Style ähnelt.
        /// </summary>
        public static string SwimmingStyleString {
            get {
                return ResourceManager.GetString("SwimmingStyleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template Filename Postfix ähnelt.
        /// </summary>
        public static string TemplateFilenamePostfixString {
            get {
                return ResourceManager.GetString("TemplateFilenamePostfixString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Forms Template ähnelt.
        /// </summary>
        public static string TimeFormsTemplatePathString {
            get {
                return ResourceManager.GetString("TimeFormsTemplatePathString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Input Millisecond Digits ähnelt.
        /// </summary>
        public static string TimeInputMillisecondDigitsString {
            get {
                return ResourceManager.GetString("TimeInputMillisecondDigitsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeInput ähnelt.
        /// </summary>
        public static string TimeInputPageTitle {
            get {
                return ResourceManager.GetString("TimeInputPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At least one time isn&apos;t set (time is zero)! ähnelt.
        /// </summary>
        public static string TimeInputWarningAtLeastOneTimeMissingString {
            get {
                return ResourceManager.GetString("TimeInputWarningAtLeastOneTimeMissingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        public static string TimeString {
            get {
                return ResourceManager.GetString("TimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total ähnelt.
        /// </summary>
        public static string TotalString {
            get {
                return ResourceManager.GetString("TotalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are unsaved changes. Should they be saved before continuing? ähnelt.
        /// </summary>
        public static string UnsavedChangesSavePromptString {
            get {
                return ResourceManager.GetString("UnsavedChangesSavePromptString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsaved changes ähnelt.
        /// </summary>
        public static string UnsavedChangesString {
            get {
                return ResourceManager.GetString("UnsavedChangesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Valid ähnelt.
        /// </summary>
        public static string ValidString {
            get {
                return ResourceManager.GetString("ValidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Variant ähnelt.
        /// </summary>
        public static string VariantString {
            get {
                return ResourceManager.GetString("VariantString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Water Flea ähnelt.
        /// </summary>
        public static string WaterFleaString {
            get {
                return ResourceManager.GetString("WaterFleaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weight Friendship (%) ähnelt.
        /// </summary>
        public static string WeightFriendshipString {
            get {
                return ResourceManager.GetString("WeightFriendshipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weight Person Pauses (%) ähnelt.
        /// </summary>
        public static string WeightPersonStartPausesString {
            get {
                return ResourceManager.GetString("WeightPersonStartPausesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weight Same Style Sequence (%) ähnelt.
        /// </summary>
        public static string WeightSameStyleSequenceString {
            get {
                return ResourceManager.GetString("WeightSameStyleSequenceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weight Single Starts (%) ähnelt.
        /// </summary>
        public static string WeightSingleStartsString {
            get {
                return ResourceManager.GetString("WeightSingleStartsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weight Start Genders (%) ähnelt.
        /// </summary>
        public static string WeightStartGendersString {
            get {
                return ResourceManager.GetString("WeightStartGendersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weight Style Order (%) ähnelt.
        /// </summary>
        public static string WeightStyleOrderString {
            get {
                return ResourceManager.GetString("WeightStyleOrderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workspace ähnelt.
        /// </summary>
        public static string WorkspacePageTitle {
            get {
                return ResourceManager.GetString("WorkspacePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workspace ähnelt.
        /// </summary>
        public static string WorkspaceString {
            get {
                return ResourceManager.GetString("WorkspaceString", resourceCulture);
            }
        }
    }
}
