//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vereinsmeisterschaften.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumsCore {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumsCore() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vereinsmeisterschaften.Core.Properties.EnumsCore", typeof(EnumsCore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exact or nearest age (prefer higher age when distance is equal) ähnelt.
        /// </summary>
        public static string CompetitionSearchModes_ExactOrNearestPreferHigher {
            get {
                return ResourceManager.GetString("CompetitionSearchModes_ExactOrNearestPreferHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exact or nearest age (prefer lower age when distance is equal) ähnelt.
        /// </summary>
        public static string CompetitionSearchModes_ExactOrNearestPreferLower {
            get {
                return ResourceManager.GetString("CompetitionSearchModes_ExactOrNearestPreferLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exact or next higher age ähnelt.
        /// </summary>
        public static string CompetitionSearchModes_ExactOrNextHigherAge {
            get {
                return ResourceManager.GetString("CompetitionSearchModes_ExactOrNextHigherAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exact or next lower age ähnelt.
        /// </summary>
        public static string CompetitionSearchModes_ExactOrNextLowerAge {
            get {
                return ResourceManager.GetString("CompetitionSearchModes_ExactOrNextLowerAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exact or max. age when person is older ähnelt.
        /// </summary>
        public static string CompetitionSearchModes_ExactOrNextLowerOnlyMaxAge {
            get {
                return ResourceManager.GetString("CompetitionSearchModes_ExactOrNextLowerOnlyMaxAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only Exact Age ähnelt.
        /// </summary>
        public static string CompetitionSearchModes_OnlyExactAge {
            get {
                return ResourceManager.GetString("CompetitionSearchModes_OnlyExactAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DOCX ähnelt.
        /// </summary>
        public static string DocumentCreationFileTypes_DOCX {
            get {
                return ResourceManager.GetString("DocumentCreationFileTypes_DOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DOCX &amp; PDF ähnelt.
        /// </summary>
        public static string DocumentCreationFileTypes_DOCX_AND_PDF {
            get {
                return ResourceManager.GetString("DocumentCreationFileTypes_DOCX_AND_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF ähnelt.
        /// </summary>
        public static string DocumentCreationFileTypes_PDF {
            get {
                return ResourceManager.GetString("DocumentCreationFileTypes_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Female ähnelt.
        /// </summary>
        public static string Genders_Female {
            get {
                return ResourceManager.GetString("Genders_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Male ähnelt.
        /// </summary>
        public static string Genders_Male {
            get {
                return ResourceManager.GetString("Genders_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition ID (1 - 9) ähnelt.
        /// </summary>
        public static string ItemOrderingsCertificate_ByCompetitionAscending {
            get {
                return ResourceManager.GetString("ItemOrderingsCertificate_ByCompetitionAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition ID (9 - 1) ähnelt.
        /// </summary>
        public static string ItemOrderingsCertificate_ByCompetitionDescending {
            get {
                return ResourceManager.GetString("ItemOrderingsCertificate_ByCompetitionDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name (A - Z) ähnelt.
        /// </summary>
        public static string ItemOrderingsCertificate_ByFirstNameAscending {
            get {
                return ResourceManager.GetString("ItemOrderingsCertificate_ByFirstNameAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name (Z - A) ähnelt.
        /// </summary>
        public static string ItemOrderingsCertificate_ByFirstNameDescending {
            get {
                return ResourceManager.GetString("ItemOrderingsCertificate_ByFirstNameDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name (A - Z) ähnelt.
        /// </summary>
        public static string ItemOrderingsCertificate_ByNameAscending {
            get {
                return ResourceManager.GetString("ItemOrderingsCertificate_ByNameAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name (Z - A) ähnelt.
        /// </summary>
        public static string ItemOrderingsCertificate_ByNameDescending {
            get {
                return ResourceManager.GetString("ItemOrderingsCertificate_ByNameDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string ItemOrderingsCertificate_None {
            get {
                return ResourceManager.GetString("ItemOrderingsCertificate_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name (A - Z) ähnelt.
        /// </summary>
        public static string ItemOrderingsOverviewList_ByFirstNameAscending {
            get {
                return ResourceManager.GetString("ItemOrderingsOverviewList_ByFirstNameAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name (Z - A) ähnelt.
        /// </summary>
        public static string ItemOrderingsOverviewList_ByFirstNameDescending {
            get {
                return ResourceManager.GetString("ItemOrderingsOverviewList_ByFirstNameDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name (A - Z) ähnelt.
        /// </summary>
        public static string ItemOrderingsOverviewList_ByNameAscending {
            get {
                return ResourceManager.GetString("ItemOrderingsOverviewList_ByNameAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name (Z - A) ähnelt.
        /// </summary>
        public static string ItemOrderingsOverviewList_ByNameDescending {
            get {
                return ResourceManager.GetString("ItemOrderingsOverviewList_ByNameDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string ItemOrderingsOverviewList_None {
            get {
                return ResourceManager.GetString("ItemOrderingsOverviewList_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Best Place (1 - 9) ähnelt.
        /// </summary>
        public static string ItemOrderingsResultListDetail_ByBestPlaceAscending {
            get {
                return ResourceManager.GetString("ItemOrderingsResultListDetail_ByBestPlaceAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Best Place (9 - 1) ähnelt.
        /// </summary>
        public static string ItemOrderingsResultListDetail_ByBestPlaceDescending {
            get {
                return ResourceManager.GetString("ItemOrderingsResultListDetail_ByBestPlaceDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name (A - Z) ähnelt.
        /// </summary>
        public static string ItemOrderingsResultListDetail_ByFirstNameAscending {
            get {
                return ResourceManager.GetString("ItemOrderingsResultListDetail_ByFirstNameAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name (Z - A) ähnelt.
        /// </summary>
        public static string ItemOrderingsResultListDetail_ByFirstNameDescending {
            get {
                return ResourceManager.GetString("ItemOrderingsResultListDetail_ByFirstNameDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name (A - Z) ähnelt.
        /// </summary>
        public static string ItemOrderingsResultListDetail_ByNameAscending {
            get {
                return ResourceManager.GetString("ItemOrderingsResultListDetail_ByNameAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name (Z - A) ähnelt.
        /// </summary>
        public static string ItemOrderingsResultListDetail_ByNameDescending {
            get {
                return ResourceManager.GetString("ItemOrderingsResultListDetail_ByNameDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string ItemOrderingsResultListDetail_None {
            get {
                return ResourceManager.GetString("ItemOrderingsResultListDetail_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competition ID ähnelt.
        /// </summary>
        public static string PersonStartFilters_CompetitionID {
            get {
                return ResourceManager.GetString("PersonStartFilters_CompetitionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string PersonStartFilters_None {
            get {
                return ResourceManager.GetString("PersonStartFilters_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Person ähnelt.
        /// </summary>
        public static string PersonStartFilters_Person {
            get {
                return ResourceManager.GetString("PersonStartFilters_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swimming Style ähnelt.
        /// </summary>
        public static string PersonStartFilters_SwimmingStyle {
            get {
                return ResourceManager.GetString("PersonStartFilters_SwimmingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backstroke ähnelt.
        /// </summary>
        public static string ResultTypes_Backstroke {
            get {
                return ResourceManager.GetString("ResultTypes_Backstroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breaststroke ähnelt.
        /// </summary>
        public static string ResultTypes_Breaststroke {
            get {
                return ResourceManager.GetString("ResultTypes_Breaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Butterfly ähnelt.
        /// </summary>
        public static string ResultTypes_Butterfly {
            get {
                return ResourceManager.GetString("ResultTypes_Butterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freestyle ähnelt.
        /// </summary>
        public static string ResultTypes_Freestyle {
            get {
                return ResourceManager.GetString("ResultTypes_Freestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max. Age Competitions ähnelt.
        /// </summary>
        public static string ResultTypes_MaxAgeCompetitions {
            get {
                return ResourceManager.GetString("ResultTypes_MaxAgeCompetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medley ähnelt.
        /// </summary>
        public static string ResultTypes_Medley {
            get {
                return ResourceManager.GetString("ResultTypes_Medley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overall ähnelt.
        /// </summary>
        public static string ResultTypes_Overall {
            get {
                return ResourceManager.GetString("ResultTypes_Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WaterFlea ähnelt.
        /// </summary>
        public static string ResultTypes_WaterFlea {
            get {
                return ResourceManager.GetString("ResultTypes_WaterFlea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backstroke ähnelt.
        /// </summary>
        public static string SwimmingStyles_Backstroke {
            get {
                return ResourceManager.GetString("SwimmingStyles_Backstroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breaststroke ähnelt.
        /// </summary>
        public static string SwimmingStyles_Breaststroke {
            get {
                return ResourceManager.GetString("SwimmingStyles_Breaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Butterfly ähnelt.
        /// </summary>
        public static string SwimmingStyles_Butterfly {
            get {
                return ResourceManager.GetString("SwimmingStyles_Butterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freestyle ähnelt.
        /// </summary>
        public static string SwimmingStyles_Freestyle {
            get {
                return ResourceManager.GetString("SwimmingStyles_Freestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medley ähnelt.
        /// </summary>
        public static string SwimmingStyles_Medley {
            get {
                return ResourceManager.GetString("SwimmingStyles_Medley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        public static string SwimmingStyles_Unknown {
            get {
                return ResourceManager.GetString("SwimmingStyles_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Water Flea ähnelt.
        /// </summary>
        public static string SwimmingStyles_WaterFlea {
            get {
                return ResourceManager.GetString("SwimmingStyles_WaterFlea", resourceCulture);
            }
        }
    }
}
