//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vereinsmeisterschaften.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vereinsmeisterschaften.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die all ähnelt.
        /// </summary>
        public static string AllString {
            get {
                return ResourceManager.GetString("AllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birth Year ähnelt.
        /// </summary>
        public static string BirthYearString {
            get {
                return ResourceManager.GetString("BirthYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The path to the LibreOffice application is empty or doesn&apos;t exist! ähnelt.
        /// </summary>
        public static string Error_LibreOffice_ApplicationPathError {
            get {
                return ResourceManager.GetString("Error_LibreOffice_ApplicationPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LibreOffice failed to convert the .docx file to a .pdf file. Error code was {0}. ähnelt.
        /// </summary>
        public static string Error_LibreOffice_ConversionFailed {
            get {
                return ResourceManager.GetString("Error_LibreOffice_ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft Word failed to convert the .docx file to a .pdf file. Error was: {0}. ähnelt.
        /// </summary>
        public static string Error_MSWord_ConversionFailed {
            get {
                return ResourceManager.GetString("Error_MSWord_ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BestRace.csv ähnelt.
        /// </summary>
        public static string FileName_BestRace {
            get {
                return ResourceManager.GetString("FileName_BestRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CompetitionDistanceRules.csv ähnelt.
        /// </summary>
        public static string FileName_CompetitionDistanceRules {
            get {
                return ResourceManager.GetString("FileName_CompetitionDistanceRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Competitions.csv ähnelt.
        /// </summary>
        public static string FileName_Competitions {
            get {
                return ResourceManager.GetString("FileName_Competitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Person.csv ähnelt.
        /// </summary>
        public static string FileName_Person {
            get {
                return ResourceManager.GetString("FileName_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not able to interpolate for {0}m {1} {2}: at least 3 points from the rudolph table inside the corresponding group (style, gender, distance) are necessary! ähnelt.
        /// </summary>
        public static string InterpolateMissingCompetitionTimesFromRudolphTableErrorFormatString {
            get {
                return ResourceManager.GetString("InterpolateMissingCompetitionTimesFromRudolphTableErrorFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Race ähnelt.
        /// </summary>
        public static string RaceString {
            get {
                return ResourceManager.GetString("RaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result Place ähnelt.
        /// </summary>
        public static string ResultPlaceString {
            get {
                return ResourceManager.GetString("ResultPlaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RudolphTableScore ähnelt.
        /// </summary>
        public static string RudolphTableScoreString {
            get {
                return ResourceManager.GetString("RudolphTableScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RudolphTable ähnelt.
        /// </summary>
        public static string RudolphTableString {
            get {
                return ResourceManager.GetString("RudolphTableString", resourceCulture);
            }
        }
    }
}
